# Generated by Django 3.2.8 on 2021-11-29 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_single', models.TextField(null=True)),
                ('answer_number', models.IntegerField(null=True)),
                ('answer_multiple', models.TextField(null=True)),
                ('answer_tf', models.IntegerField(null=True)),
                ('answer_text', models.TextField(null=True)),
                ('answer_other', models.TextField(null=True)),
                ('answer_sentiment', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cetegory_name', models.CharField(max_length=255, null=True)),
                ('cetegory_name_eng', models.CharField(max_length=255, null=True)),
                ('cetegory_slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('consumer_id', models.AutoField(primary_key=True, serialize=False)),
                ('consumer_email', models.EmailField(max_length=255, null=True, unique=True)),
                ('consumer_fname', models.CharField(max_length=255, null=True)),
                ('consumer_lname', models.CharField(max_length=255, null=True)),
                ('consumer_dob', models.DateField(null=True)),
                ('consumer_gender', models.CharField(max_length=10, null=True)),
                ('consumer_province', models.CharField(max_length=255, null=True)),
                ('consumer_address', models.TextField(null=True)),
                ('consumer_postal', models.CharField(max_length=10, null=True)),
                ('consumer_phone', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='enturpreneur',
            fields=[
                ('enturpreneur_id', models.AutoField(primary_key=True, serialize=False)),
                ('enturpreneur_email', models.CharField(max_length=255, null=True)),
                ('bissiness_name', models.CharField(max_length=255, null=True)),
                ('enturpreneur_fname', models.CharField(max_length=255, null=True)),
                ('enturpreneur_lname', models.CharField(max_length=255, null=True)),
                ('enturpreneur_idcard', models.CharField(max_length=13, null=True)),
                ('enturpreneur_province', models.CharField(max_length=255, null=True)),
                ('enturpreneur_address', models.TextField(null=True)),
                ('enturpreneur_postal', models.CharField(max_length=10, null=True)),
                ('enturpreneur_phone', models.CharField(max_length=255, null=True)),
                ('juristic_code', models.CharField(max_length=13)),
                ('juristic_document', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product_and_service',
            fields=[
                ('product_and_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_and_service_name', models.CharField(max_length=255)),
                ('product_and_service_deail', models.TextField(null=True)),
                ('product_and_service_image', models.ImageField(null=True, upload_to='product')),
                ('product_and_service_amount', models.IntegerField(null=True)),
                ('product_and_service_status', models.BooleanField(default=True, null=True)),
                ('product_and_service_create', models.DateTimeField(auto_now_add=True)),
                ('product_and_service_update', models.DateTimeField(auto_now=True)),
                ('product_and_service_slug', models.SlugField(max_length=255, null=True)),
                ('product_option_gender', models.CharField(max_length=10, null=True)),
                ('product_option_province', models.CharField(max_length=10, null=True)),
                ('cetegory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.category')),
                ('enturpreneur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.enturpreneur')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_single', models.TextField(null=True)),
                ('question_number', models.TextField(null=True)),
                ('question_tf', models.TextField(null=True)),
                ('question_multiple', models.TextField(null=True)),
                ('question_multi_1', models.TextField(null=True)),
                ('question_multi_2', models.TextField(null=True)),
                ('question_multi_3', models.TextField(null=True)),
                ('question_multi_4', models.TextField(null=True)),
                ('question_text', models.TextField(null=True)),
                ('product_and_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.product_and_service')),
            ],
        ),
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('sentiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentiment_list', models.TextField(null=True)),
                ('sentiment_status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_question', models.CharField(max_length=255, null=True)),
                ('survey_answer', models.CharField(max_length=255, null=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.answer')),
                ('product_and_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.product_and_service')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.question')),
            ],
        ),
        migrations.CreateModel(
            name='survey_has_product',
            fields=[
                ('survey_has_product', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.product_and_service')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.survey')),
            ],
        ),
        migrations.CreateModel(
            name='trial',
            fields=[
                ('trial_id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_amoun', models.IntegerField(null=True)),
                ('trial_status', models.IntegerField(null=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.consumer')),
                ('enturpreneur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.enturpreneur')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.product_and_service')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, null=True)),
                ('type_name_eng', models.CharField(max_length=255, null=True)),
                ('type_slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trial_has_survey',
            fields=[
                ('trial_has_survey', models.AutoField(primary_key=True, serialize=False)),
                ('trial_amoun', models.IntegerField(null=True)),
                ('survey_has_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.survey_has_product')),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.trial')),
            ],
        ),
        migrations.CreateModel(
            name='trial_has_product',
            fields=[
                ('trial_has_product', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.product_and_service')),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.survey')),
            ],
        ),
        migrations.AddField(
            model_name='product_and_service',
            name='type_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.type'),
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.consumer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='product_and_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.product_and_service'),
        ),
    ]
