# Generated by Django 3.2.8 on 2021-11-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_number',
            field=models.FloatField(null=True),
        ),
    ]
